// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MovieSelection.Recommendation
{
    public partial class RateMLModel
    {
        /// <summary>
        /// model input class for RateMLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Id")]
            public float Id { get; set; }

            [ColumnName(@"Directing")]
            public float Directing { get; set; }

            [ColumnName(@"Entertainment")]
            public float Entertainment { get; set; }

            [ColumnName(@"Actors")]
            public float Actors { get; set; }

            [ColumnName(@"Plot")]
            public float Plot { get; set; }

            [ColumnName(@"Value")]
            public float Value { get; set; }

            [ColumnName(@"MovieId")]
            public float MovieId { get; set; }

            [ColumnName(@"UserId")]
            public string UserId { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for RateMLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("RateMLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
